n[0:2] => row[0] and column[2]
n[-1]

In [10]:
n= [1,2,3]
print(n[0:2])
print(n[-1])
print(n[-2])


[1, 2]
3
2


In [11]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[1,2])
print(a[0:2,2])
print(a[-1])
print(a[:,1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[3 6]
[7 8 9]
[[2 3]
 [5 6]
 [8 9]]


In [12]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
for row in a:
    print(row)

for row in a:
    for i in row:
        print(i)
        
for f in a.flat:
    print(f)
    
    


[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9


In [13]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
print(a)
print(b)



ab = np.vstack((a,b))
print(ab)
ab1 = np.hstack((a,b))
print(ab1)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [14]:
import numpy as np
a = np.arange(30).reshape(2,15)
print(a)
a3 = np.hsplit(a,3)
print(a3)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]


In [15]:
import numpy as np
a = np.arange(30).reshape(2,15)
print(a)
a3 = np.vsplit(a,2)
print(a3)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]


In [16]:
a = np.arange(12).reshape(3,4) 
b = a>4 
print(b)
print(a[b])
a[b]=-1
print(a)
print(b)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [17]:
a = np.arange(12).reshape(3,4)
print(a)

for f in a.flatten():
    print(f)
    
for f in np.nditer(a,order='F'):
    print(f)
    
for f in np.nditer(a,order='F',flags=['external_loop']):
    print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11
0
4
8
1
5
9
2
6
10
3
7
11
[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]
